services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - ratelimiter
  redis:      
    image: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass goexpert
    ports:
      - "6379:6379"
    volumes: 
      - redisdata:/data
    networks:
      - ratelimiter   
    
networks:
  ratelimiter:

volumes:
  redisdata: