services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - ratelimiter
  redis:      
    image: redis
    ports:
      - "6379:6379"
    
networks:
  ratelimiter: