GET http://localhost:8080/songs
API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI1MjUxOTksImtleSI6ImFkbWluIiwicmwtbWF4LXJlcXVlc3RzIjoyLCJybC1zZWNvbmRzLWJsb2NrZWQiOjYwfQ.t8TRma0IHZVEdt8XaoXH2bqkK3oAQ8Ab7imFygfe5dE

###

POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin",
    "maxRequests" : 2,
    "blockedSeconds" : 60
}