GET http://localhost:8080/songs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDE3Mjc5OTcsInN1YiI6ImFkbWluIn0.URRlY2HDSa48UTdAzl0bdwCsle06f_iu_g21HbCEG38

###

POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin"
}