GET http://localhost:8080/songs
API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDE3OTMyMjksInJsLW1heC1yZXF1ZXN0cyI6Miwicmwtc2Vjb25kcy1ibG9ja2VkIjo2MCwidXNlciI6ImFkbWluIn0.qzuROXwyvVYmy8YKisMMEivDexQl1cvkH30-jF4deWE

###

POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin",
    "ratelimiterMaxRequests" : 2,
    "raterlimiterSecondsBlocked" : 60
}